### ISSUE TITLE
问个问题 如何配置.env环境文件

### ISSUE THREAD

**Issue by 502647092** [cuigh/swirl#10]

**Comment by 502647092** [comment]
是编排的.env 就是整个编排的所有服务都需要的环境变量

**Comment by cuigh** [comment]
这是个问题，因为 Swirl 是一个 Web 管理工具，跟官方的 cli 工具不一样，没有上下文目录的概念，所以 stack 中如果依赖外部文件的话没有办法支持（除非把这些文件放到 Swirl 中管理起来，也许将来可以考虑加上...也许）
