### ISSUE TITLE
部分任务无法移除

### ISSUE THREAD

**Issue by 502647092** [cuigh/swirl#12]
![image](https://user-images.githubusercontent.com/10203793/39617128-0d0a987e-4fb1-11e8-98c6-fd6dcfdb4827.png)
服务已经移除了 但是任务还在 处于pending状态 而且点击服务是不存在的
![image](https://user-images.githubusercontent.com/10203793/39617153-2665bace-4fb1-11e8-84ff-069a22b8e693.png)

**Comment by 502647092** [comment]
![image](https://user-images.githubusercontent.com/10203793/39617176-3e5a96ae-4fb1-11e8-8a9a-ad354b3d0b2b.png)

**Comment by cuigh** [comment]
这个应该是 Docker 自身的 bug

**Comment by 502647092** [comment]
好吧 反正也不影响使用 就是多了一条数据
