### ISSUE TITLE
请问一下 怎麼通过 Prometheus 创建图表 有什么文档推荐一下

### ISSUE THREAD

**Issue by 502647092** [cuigh/swirl#13]

**Comment by cuigh** [comment]
其实跟 Grafana 之类的工具写法是一样的，具体可以参考 [Prometheus](https://prometheus.io/) 官方文档，另外这里也有几个示例：#7

**Comment by 502647092** [comment]
@cuigh 请教一下 网络流量监控的语法怎么写 研究了半天没搞懂

**Comment by cuigh** [comment]
网络流量监控服务状态页已经内置了吧，查询表达式是(依赖 cadvisor 数据)：

* **Receive**: `sum(irate(container_network_receive_bytes_total{container_label_com_docker_swarm_service_name="${service}"}[5m])) by(name)`
* **Send**: `sum(irate(container_network_transmit_bytes_total{container_label_com_docker_swarm_service_name="${service}"}[5m])) by(name)`

**Comment by 502647092** [comment]
@cuigh emm 我想要的是node节点的网络统计

**Comment by cuigh** [comment]
这个推荐用 **[node-exporter](https://github.com/prometheus/node_exporter)**，查询表达式示例：`sum(irate(node_network_receive_bytes_total[5m])) by(host_name)`

**Comment by 502647092** [comment]
@cuigh 
![image](https://user-images.githubusercontent.com/10203793/42018624-47964bf0-7ae5-11e8-9312-808c39c18f77.png)
这个是怎么回事儿 百分比好多小数点
![image](https://user-images.githubusercontent.com/10203793/42018660-5d30a4a6-7ae5-11e8-856b-bb324ca6b5f6.png)
这个是配置

**Comment by cuigh** [comment]
把图表的单位设置为 None 吧，Gauge 类型的图表目前对单位的处理不够完善

**Comment by 502647092** [comment]
@cuigh 还有就是希望可以叠加多条查询的结果 比如 入网出网同一个图标显示

**Comment by cuigh** [comment]
这个之前我也考虑过，不过在现在的版本上修改我需要先想好一个比较好的向下兼容方案

**Comment by cuigh** [comment]
@502647092 v0.8.1 已经支持单图表多指标

**Comment by matri** [comment]
hello，我添加图表的时候有一些问题，不确定哪里做错了，麻烦帮忙看一下：

Prometheus的情况是这样的：

![prometheus](https://user-images.githubusercontent.com/330327/53693641-59caae80-3dde-11e9-9b3f-b97064438ce8.jpg)

然后swirl的配置是这样的，也按要求重启了swirl service：

![swirl](https://user-images.githubusercontent.com/330327/53693649-6cdd7e80-3dde-11e9-817c-b189df48a9d5.jpg)

然后我在swirl后台增加图表的时候，一直报这样的错：

![error](https://user-images.githubusercontent.com/330327/53693680-d9f11400-3dde-11e9-81f5-ac7aba86f5c5.jpg)

不知道还有哪里有问题，swirl也没有错误日志，谢谢！另外fork版的 Prometheus 是否有使用指引？

**Comment by cuigh** [comment]
没有录入 Metrics 吧：
[cid:7B58D724-7D2C-4C1D-B8A5-8E95041A7239]

在 2019年3月3日，下午6:06，matri <notifications@github.com<mailto:notifications@github.com>> 写道：


hello，我添加图表的时候有一些问题，不确定哪里做错了，麻烦帮忙看一下：

Prometheus的情况是这样的：

[prometheus]<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F330327%2F53693641-59caae80-3dde-11e9-9b3f-b97064438ce8.jpg&data=02%7C01%7C%7Ce517af159d5a4a52517708d69fbfefcc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636872044035638174&sdata=ZNfpSePwRnlRd148BO04P%2F3MOjXedxbnAwx5SPc90u0%3D&reserved=0>

然后swirl的配置是这样的，也按要求重启了swirl service：

[swirl]<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F330327%2F53693649-6cdd7e80-3dde-11e9-817c-b189df48a9d5.jpg&data=02%7C01%7C%7Ce517af159d5a4a52517708d69fbfefcc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636872044035648185&sdata=YnMItSx8mstnZ%2B6%2FRpY%2FR7c6t6dLDzI7ctM7%2FFFWW5k%3D&reserved=0>

然后我在swirl后台增加图表的时候，一直报这样的错：

[error]<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F330327%2F53693680-d9f11400-3dde-11e9-81f5-ac7aba86f5c5.jpg&data=02%7C01%7C%7Ce517af159d5a4a52517708d69fbfefcc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636872044035658189&sdata=ZS9pXLSSAsMCEY%2BjNPTbfGDMSV3eHihL%2FMNOJCRKWco%3D&reserved=0>

不知道还有哪里有问题，swirl也没有错误日志，谢谢！另外fork版的 Prometheus 是否有使用指引？

**Comment by cuigh** [comment]
1. 没有录入 Metrics 吧
![Metrics](https://user-images.githubusercontent.com/1681556/53714084-1298f800-3e88-11e9-842e-f7cb5e7377a4.png)

2. Prometheus 的说明在 Docker hub 上有：[Prometheus](https://cloud.docker.com/u/cuigh/repository/docker/cuigh/prometheus)

**Comment by matri** [comment]
感谢回复，我不确定您说的录入 Metrics 是什么概念，因为在 Prometheus 上面我是可以搜索各种 Metrics的，swirl 我尝试增加的图表也是复制您在另外一个 issue 里面给的样例，不知道是不是我漏了什么东西？

**Comment by cuigh** [comment]
看我上面的截图，图表这一块后来有调整，之前 issue 中的示例有些过时了（不过我刚修改了）

**Comment by matri** [comment]
> 看我上面的截图，图表这一块后来有调整，之前 issue 中的示例有些过时了（不过我刚修改了）

看明白了，应该是调整了以后之前的那个示例不能用了，因为我一直用导入功能测试，还以为是我配置有问题，现在ok了，非常感谢！
