### ISSUE TITLE
How to integrate Prometheus monitoring with cuigh/swirl? Waiting for your reply

### ISSUE THREAD

**Issue by sudipto92** [cuigh/swirl#15]

**Comment by cuigh** [comment]
You cant set address of Prometheus on 'System>Settings' page.
<img width="576" alt="prometheus" src="https://user-images.githubusercontent.com/1681556/40610405-d588afc4-62a4-11e8-8240-e7447e15f4be.png">

**Comment by cuigh** [comment]
BTW, you may need my fork version of [Prometheus](https://hub.docker.com/r/cuigh/prometheus/) for better experience.

**Comment by sudipto92** [comment]
I have set the promethus url but it is not reflected on swril.

**Comment by cuigh** [comment]
You also need [cadvisor](https://github.com/google/cadvisor) to collect container metrics. I'll add this to README later.

**Comment by sudipto92** [comment]
Hi Cuigh,
I have added the Prometheus url but it is not reflected on Swril.

**Comment by cuigh** [comment]
Fixed, it’s a bug when using **bolt** storage engine.
