### ISSUE TITLE
是否可以提供Token登录的方式

### ISSUE THREAD

**Issue by 502647092** [cuigh/swirl#16]
@cuigh 主要是用于直接操作swirl的rest接口直接重启服务或者上下线编排

**Comment by cuigh** [comment]
暂时估计没有时间弄，后续会考虑，先模拟 Form 认证凑合用吧:smile:。我最近也在考虑 Swirl 自身的 API 到底以怎样的方式暴露更好。

**Comment by 502647092** [comment]
@cuigh 主要是目前 Jenkins自动构建结束之后 我还得手动重启编排 比较麻烦

**Comment by cuigh** [comment]
@502647092 已经支持 Token 认证(v1.0.0rc1+)
