### ISSUE TITLE
权限管理是不是有问题 给了权限但是还是显示403

### ISSUE THREAD

**Issue by 502647092** [cuigh/swirl#2]
![image](https://user-images.githubusercontent.com/10203793/37443322-578fecba-2846-11e8-8ec7-9787d0ead0d9.png)
![image](https://user-images.githubusercontent.com/10203793/37443332-63a03be0-2846-11e8-96d7-0a40e0bc1cca.png)
![image](https://user-images.githubusercontent.com/10203793/37443335-6b7e915e-2846-11e8-8b3d-3687d0d29ff1.png)

**Comment by cuigh** [comment]
基于性能考虑，目前角色权限有三分钟的内存缓存

**Comment by 502647092** [comment]
@cuigh 好的 知道了
