### ISSUE TITLE
Https的情况下WebSocket链接异常

### ISSUE THREAD

**Issue by 502647092** [cuigh/swirl#21]
在HTTPS的情况下 WebSocket没有使用wss导致无法链接 希望修复一下

**Comment by cuigh** [comment]
已修复

**Comment by 502647092** [comment]
@cuigh 能不能麻烦一下 推送到DockerHub

**Comment by cuigh** [comment]
已更新：cuigh/swirl:latest

在 2018年8月15日，09:43，蒋天蓓 <notifications@github.com<mailto:notifications@github.com>> 写道：


@cuigh<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcuigh&data=02%7C01%7C%7C068a3a8dca584d2d489008d602507984%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636698941983219502&sdata=JiXf09C2%2BTbnAVxRl00gIMTCtoSV941xFuOMYYzFIgM%3D&reserved=0> 能不能麻烦一下 推送到DockerHub
