### ISSUE TITLE
go.sum checksum error

### ISSUE THREAD

**Issue by prologic** [cuigh/swirl#26]
Hi! I'm trying to build this locally to hack on / contribute to but I *think* there's a checksum error with the docker client dependency:

```
prologic@Jamess-MacBook
Sat Apr 13 14:06:42
~/Contributions/swirl
 (master) 0
$ go build
go: downloading github.com/docker/docker v0.0.0-20180415161252-ea579a619452
go: verifying github.com/docker/docker@v0.0.0-20180415161252-ea579a619452: checksum mismatch
	downloaded: h1:KXTxrc9Q8FwG8x/lbSBYzBMKn3xWpwx9MBfP1Ko7FYg=
	go.sum:     h1:3DHHYhTKAP1ZgL0g+msknSuFuZBA0UW6BqcAA5qsWWc=
```

Can you look in to this? Perhaps consider upgrading this dependency (*not trivial as the library has changed some API*)

**Comment by cuigh** [comment]
I use [athens](https://github.com/gomods/athens) to manage public go modules, it seems that athens adjust checksum from v0.3

**Comment by cuigh** [comment]
Go 1.11.4 introduced a breaking [change](https://github.com/golang/go/issues/30369) that broke checksum calculations. I'll fix it soon.

**Comment by cuigh** [comment]
I've updated docker module, It should be OK now.
