### ISSUE TITLE
Issue: Cannot connect to the Docker daemon at unix:///var/run/docker.sock.

### ISSUE THREAD

**Issue by angeloluidens** [cuigh/swirl#31]
Hi,

I am getting the following message in my browser after I login to Swirl: "Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"

Could provide my with advise or direction what I am missing or doing wrong?

Below is my docker-compose file section for starting Swirl and MongoDB:

`  swirl:
    image: cuigh/swirl
    container_name: swirl
    depends_on:
      - mongo
    ports:
      - 8001:8001
    environment:
    #  - DB_TYPE=bolt
      - PGID=998
      - DB_ADDRESS=/data/swirl
      - DB_ADDRESS=mongo:27017/swirl     # - DB_ADDRESS=/data/swirl
    #  - RESCRAMBLE=true
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined      
    volumes:
      - /var/run/docker.sock,dst=/var/run/docker.sock
      - /var/lib/docker/:/var/lib/docker:ro
      - /path/swirl/data=/data/swirl
    networks:
      - web
      - net
    deploy:
    #  privileged: true
      mode: replicated
      replicas: 1
      update_config:
        order: start-first		# get new container running first before removing old, for less downtime
      rollback_config:
        order: start-first		# get new container running first before removing old, for less downtime
      placement:
        constraints:
           - node.role==manager

  mongo:
    image: mongo
    volumes:
      - /path/mongo/data:/data/db
    networks:
      - net
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: start-first		# get new container running first before removing old, for less downtime
      rollback_config:
        order: start-first		# get new container running first before removing old, for less downtime
#      placement:
#        constraints: [node.hostname == mongo]`

Thank you in advance.
Regards,
Angelo

**Comment by RuiSiang** [comment]
1. Check if docker service is running
2. That error is likely a result of running docker in docker, refer to [this article](https://itnext.io/docker-in-docker-521958d34efd)

**Comment by robinwangrubin** [comment]
It looks like your Docker didn't run.  check the sock file:/var/run/docker.sock
