### ISSUE TITLE
在swirl中创建表格失败

### ISSUE THREAD

**Issue by jiujiujiujiujiuaia** [cuigh/swirl#32]
您好，想向你请教关于在swirl中 创建表格问题。

我创建的表格显示是空白，如下：

![KX%{`P N%0Z7UD9X4 OTIHY](https://user-images.githubusercontent.com/27950614/80005989-e068b080-84f6-11ea-9a44-cef05d9314da.png)

这两个空格的仪表盘表达式参考的是您的这个配置：

![VF6~8J~RQXXRO6I{~GNAX_7](https://user-images.githubusercontent.com/27950614/80005650-74864800-84f6-11ea-924c-cd3a518c17de.png)
![C)YDM6SV 8O6@E}DET@TR N](https://user-images.githubusercontent.com/27950614/80005655-75b77500-84f6-11ea-80b9-18e3e451eea9.png)

我的设置如下（启动普罗米修斯后有重启整个服务）：
![image](https://user-images.githubusercontent.com/27950614/80005719-8d8ef900-84f6-11ea-87f3-5cb932dfd43a.png)

普罗米修斯的页面如下：
![image](https://user-images.githubusercontent.com/27950614/80005878-c5963c00-84f6-11ea-971f-3b42d73c6cca.png)

感谢您耐心的阅读，麻烦您看下这个问题该如何解决

**Comment by cuigh** [comment]
首先你得让 Prometheus 正确的采集到数据，我那两个图表配置示例依赖的是 [cAdvisor](https://github.com/google/cadvisor) 采集的数据，你配置好 cAdvisor 并让 Prometheus 采集数据就可以了
