### ISSUE TITLE
请问如何成功指定 --constraint 'node.role == worker' 

### ISSUE THREAD

**Issue by max27149** [cuigh/swirl#33]
您好，我的swarm测试集群是1manager+2worker，
因为有--mount="type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock"  ，我理解的是创建swirl服务必须在manager上执行。
想请教您一下 --constraint 'node.role == worker' 是怎么实现的？

**Comment by cuigh** [comment]
```
docker service create \
  --name=swirl \
  --publish=8001:8001/tcp \
  --env DB_TYPE=bolt \
  --env DB_ADDRESS=/data/swirl \
  --constraint=node.role==manager \
  --mount=type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
  --mount=type=bind,src=/data/swirl,dst=/data/swirl \
  cuigh/swirl
```

**Comment by max27149** [comment]
> ```
> docker service create \
>   --name=swirl \
>   --publish=8001:8001/tcp \
>   --env DB_TYPE=bolt \
>   --env DB_ADDRESS=/data/swirl \
>   --constraint=node.role==manager \
>   --mount=type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
>   --mount=type=bind,src=/data/swirl,dst=/data/swirl \
>   cuigh/swirl
> ```

您这个还是用manager节点去启动swirl，我的意思是如何让swirl跑在worker上？像下图这样：
<img width="643" alt="1" src="https://user-images.githubusercontent.com/47019171/85013917-f3ff6300-b197-11ea-92ca-8140eaa25e09.png">

**Comment by cuigh** [comment]
worker 节点不支持管理 API，你需要在 manager 节点上先部署一个 docker-proxy 服务，然后通过 docker-proxy 访问 Swarm 的管理 API
```
docker service create 
--name swirl 
--replicas 2 
--network docker-proxy 
--constraint 'node.role == worker' 
--env 'DB_ADDRESS={db address}' 
--env 'DOCKER_ENDPOINT=tcp://docker-proxy:2375' 
--env 'AUTH_TIMEOUT=4h' 
--env 'DOCKER_API_VERSION=1.37' 
cuigh/swirl:0.8.4
```

**Comment by max27149** [comment]
收到，多谢
