### ISSUE TITLE
docker stack deploy 启动不成功

### ISSUE THREAD

**Issue by baiyea** [cuigh/swirl#34]
我是直接采用 docker stack 启动的。
![image](https://user-images.githubusercontent.com/8907916/105319433-d4358f00-5bff-11eb-908d-d8f65d04e3e3.png)

查看日志报错
![image](https://user-images.githubusercontent.com/8907916/105319365-bb2cde00-5bff-11eb-9b7d-a7350d47f411.png)

**Comment by cuigh** [comment]
这是连不上数据库，应该是因为 Swirl 跟 MongoDB 不在同一个网络

**Comment by baiyea** [comment]
感谢回复～。
那请问如何修复这个问题。我是直接用的简介中的compose.yaml文件，没有修改的呀。
我在启动的过程中查看，是有新建网络的。这是我本地的docker问题么？
![image](https://user-images.githubusercontent.com/8907916/105325028-17dfc700-5c07-11eb-9d1c-573a6ad5a298.png)

**Comment by cuigh** [comment]
应该是 mongo 服务的镜像没下载完成，运行 `docker service ps swirl_mongo` 查看服务是否是 Running 状态：
![image](https://user-images.githubusercontent.com/1681556/105330616-79a32f80-5c0d-11eb-9369-ca83b0d361ea.png)
