### ISSUE TITLE
最新代码登录失败

### ISSUE THREAD

**Issue by Qiuser** [cuigh/swirl#37]
昨天克隆仓库后直接docker build，首先是用bolt类型的数据库，然后容器启动失败，日志报
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa75e18]

goroutine 1 [running]:
github.com/boltdb/bolt.(*Bucket).ForEach(0xc00032a2b8, 0xc00025f038)
	/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/bucket.go:385 +0x18

然后换mongodb，这是我两个容器的启动参数

docker run --name mongo -d -p 27017:27017 mongo
docker run -d -p 80:8001 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -e DB_TYPE=mongo \
    -e DB_ADDRESS=mongodb://192.168.3.70:27017/swirl \
    --name=swirl \
    swirl:test-v1

换mongo之后启动成功了，并且Web页面能进入，但是在设置登录名跟密码之后登录失败。
![Q~6RJUY } JH~E(~A)WZKIH](https://user-images.githubusercontent.com/31086983/150459337-0f3843fe-3d6f-430d-bafa-996b51d18056.png)
![Q}3%PY5I50O 11~O_5__J R](https://user-images.githubusercontent.com/31086983/150459345-32d8a5e2-7089-480f-9842-e8b57379d58f.png)
密码设置的123456，登录失败，swirl容器也查不到详细的日志。

**Comment by alanland** [comment]
我用的 `cuigh/swirl:1.0.0rc1`  这个 Docker 镜像， 也遇到了同样问题，初始化密码之后登录都是提示失败。删库重试了多次。

**Comment by cuigh** [comment]
@Qiuser @alanland Fixed in version 1.0.0rc2.
