### ISSUE TITLE
提几个功能上的需求

### ISSUE THREAD

**Issue by 502647092** [cuigh/swirl#4]
1. 日志的实时展示
2. 多服务日志展示
3. 服务内部命令执行

最近正好在学习Go相关的内容 有时间的话我自己也会试着写写看 提交PR

**Comment by cuigh** [comment]
好，这几个功能后续会考虑，能提交 PR 就更欢迎了~

**Comment by 502647092** [comment]
@cuigh 就是多个服务日志显示在同一个地方
用DockerCompose直接up的那种效果

**Comment by qq12157138** [comment]
@cuigh 针对我提的第二个需求，还有一点就是，希望增加图表展示各种指标，logo左上角有就行了，占这么大地方毕竟是管理工具不是官网首页，没啥意思。

**Comment by qq12157138** [comment]
@cuigh 我今天更新cuigh/swirl了，监控那个添加按钮点了没反应。
这个是兼容问题，safari不出弹框，chrome有弹框

**Comment by cuigh** [comment]
1. 自定义监控这个功能还没完全实现，只有 latest 标签中才有这个按钮。按钮不能点击应该是浏览器脚本缓存的问题，因为 latest 没有更新版本号，生产环境建议使用稳定版不要用 latest。

**Comment by qq12157138** [comment]
@cuigh  界面我觉得这中就超级爽
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/15812485/37638600-a9450832-2c48-11e8-9dd8-c29eddc9d052.png">
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/15812485/37638606-b973cc8e-2c48-11e8-857b-e263d5174f24.png">

<img width="1384" alt="image" src="https://user-images.githubusercontent.com/15812485/37638554-71e09172-2c48-11e8-8ef6-543d7e696b12.png">

**Comment by cuigh** [comment]
会参考 grafana，不过应该不会做得这么灵活，毕竟 **Swirl** 的焦点还是放在 Docker 和 Swarm 自身上。

**Comment by cuigh** [comment]
@502647092 除了第二点，v0.8.0 已经实现

**Comment by 502647092** [comment]
@cuigh emm 还有一个问题就是 现在容器只能看到单机的 能不能通过配置添加多个机器的容器查看

**Comment by cuigh** [comment]
受限于 Docker Engine，容器、镜像、数据卷的 API 目前都是单机的，这使得这些 API 在 Swarm 下几乎没有太大的价值。为解决这个问题，后续会开发一个辅助服务 [swirl-agent](https://github.com/cuigh/swirl-agent)，预计会在 v1.0 之前发布。

**Comment by qq12157138** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
我觉得你参考一下portainer吧，他那个只要暴漏docker的远程操控就可以支持多集群



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    




    在2018年06月15日 13:02，cuigh<notifications@github.com> 写道： 


受限于 Docker Engine，容器、镜像、数据卷的 API 目前都是单机的，这使得这些 API 在 Swarm 下几乎没有太大的价值。为解决这个问题，后续会开发一个辅助服务 swirl-agent，预计会在 v1.0 之前发布。

**Comment by qq12157138** [comment]
我觉得你参考一下portainer吧，他那个只要暴漏docker的远程操控就可以支持多集群

**Comment by cuigh** [comment]
多集群支持在实现上没有任何难道，不过在 1.0 之前暂时不会考虑；Swirl 跟 Portainer 的专注点不太一样，更倾向于在完善基本功能的同时扩展 Swarm 本身比较缺乏的功能，如：

* 监控(已实现)
* 弹性扩容(已实现)
* 灰度发布与蓝绿发布(TODO)
* More...

在支持这些功能后，Swarm 将可以成为一个简化版的 K8S，非常适合中小型公司在生产环境使用。
