### ISSUE TITLE
登录的时候有一个报错

### ISSUE THREAD

**Issue by 502647092** [cuigh/swirl#8]
![image](https://user-images.githubusercontent.com/10203793/39613170-fa9ec4bc-4f97-11e8-93d3-1c1215b0bb5c.png)

**Comment by cuigh** [comment]
你用的是 LDAP 帐号还是内置帐号？

**Comment by 502647092** [comment]
@cuigh 内置的账号 账号密码错误的时候出现的

**Comment by cuigh** [comment]
Fixed, thx.
